config/routes.rb
Rails.application.routes.draw do
  resources :questions do
    resources :answers, except: %i[:index]
    resources :comments, except: %i[:index]
  end

  resources :answers, except: %i[:index] do
    resources :comments, except: %i[:index]
  end
  
  root "questions#index"
  
  
  devise_for :users
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  question_id :integer
#  content     :text
#  rating      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  has_many :comments, as: :commentable
  has_many :votes, as: :votable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  commentable_type :string
#  commentable_id   :integer
#  user_id          :integer
#  content          :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  title      :string
#  content    :text
#  rating     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :comments, as: :commentable
  has_many :votes, as: :votable

  def self.search(search)
    search ? where(['title LIKE ?', "%#{search}%"]) : all
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def username
    self.email.split('@')[0].capitalize
  end
end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id           :integer          not null, primary key
#  votable_type :string
#  votable_id   :integer
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Vote < ApplicationRecord
  belongs_to :votable, polymorphic: true
  belongs_to :user
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # before_action :set_answer, except: [:create]
  # before_action :set_question, only: [:create, :update, :destroy]
  

  
  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user    
  
    respond_to do |format|    
      if @answer.save
        format.html { redirect_to question_path(@question), notice: 'Answer was successfully created.'}
        format.js
        #format.json {render :show, status: :created, location: @answer }        
      else
        format.html { redirect_to question_path(@question), alert: 'Error, please try again.'}
        format.js        
      end     
    end    
  end

  def destroy
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html {redirect_to question_path(@question) }
      format.js
    end    
  end






  private

  # def set_question
  #   @question = Question.find(params[:question_id])
  # end

  # def set_answer
  #   @answer = @question.answers.find(params[:id])
  # end

  def answer_params
    params.require(:answer).permit(:content)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @parent = comment_type
        @comment = @parent.comments.new(comment_params)    

        respond_to do |format|
            if @comment.save
                format.html { redirect_to question_path(@parent.question_id) } if @commentable_type == 'Answer'
                format.html { redirect_to quesion_path(@parent) } if @commentable_type == 'Question'
                format.js
            else
                format.html {'questions/show'}
                flash[:error] = 'Error, comment not added'
            end
        end
    end




    private


    def comment_type
        if params[:question_id]
            Question.find(params[:question_id])
        else
            Answer.find(params[:answer_id])
        end    
    end

    def comment_params
        params.require(:comment).permit(:content).merge(user_id: current_user.id)    
    end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]


  def index
    @questions = Question.search(params[:search]).order(created_at: :desc)
  end

  def new
    @question = Question.new
    @question.user = current_user
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    
    if @question.save
      flash[:notice] = "Pregunta creada correctamente"
      redirect_to root_path
    else
      render :new
    end  
  end


  def show
    
  end





  private

  def set_question
    @question = Question.find(params[:id])
  end


  def question_params
    params.require(:question).permit(:user_id, :title, :content)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
    
    def create
        @parent = vote_type
        @vote = @parent.votes.create(user: current_user)

        redirect_to question_path(@parent.question_id) if @vote.votable_type == 'Answer'
        redirect_to question_path(@parent) if @vote.votable_type == 'Question'
    end

    def destroy
        @parent = vote_type
        @vote = @parent.vote.where(user: current_user).take.try(:destroy)

        redirect_to question_path(@parent.question_id) if @vote.votable_type == 'Answer'
        redirect_to question_path(@parent) if @vote.votable_type == 'Question'
    end




    private
    def vote_type
        if params[:question_id]
            Question.find(params[:question_id])
        else
            Answer.find(params[:answer_id])
        end    
    end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

    def flash_msg(key)
        case key
            when 'notice' then 'alert alert-dismissible alert-info'
            when 'success' then 'alert alert-dismissible alert-success'  
            when 'error' then 'alert alert-dismissible alert-danger'  
            when 'alert' then 'alert alert-dismissible alert-warning'
        end    
    end

    def gravatar_url(email, size)
        gravatar_id = Digest::MD5::hexdigest(email).downcase  
        default_url = "http://mysite.com/myavatar.png" # Acá puedo poner una ruta para una imagen propia.  
        default_url = "retro"  
        url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}&d=#{CGI::escape(default_url)}"  
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.erb
<div class="d-inline-flex w-100" id="answer-<%= answer.id %>">
    <div class="col-2">
        <div class="text-center align-content-center">
            <span class="fa fa-thumbs-o-up"></span>
            <br>
            <span>0</span>
            <br>
            <span class="fa fa-thumbs-o-down"></span>
        </div>
    </div>
        
    <div class="col-10">                            
        <div class="align-content-center">
            <p><%= answer.content %></p> 
            <%= link_to "Borrar", [answer.question, answer], method: :delete, data:{ confirm: "Estás seguro de eliminar su respuesta?"}, remote: true %>
        </div>

        <%= link_to "Comentarios ", "#", class: 'show-comments', data: {'js-show-question-comments-link' => true} %> <span id="count-comments-question"> ( <%= answer.comments.count() %>) </span>
        <div id="show-commnents-answer">
            <div id="comments-answers-list">
                <%= render answer.comments %>
                <!-- muestra lista de comentarios de esa respuesta -->
            </div>
            <div class="mb-5" id="question-comment-form">
                <%= render  "comments/form", commentable: answer %>
                <!-- muestra formulario de comentarios para esa respuesta -->
            </div>
            <hr>
        </div>
    </div>
</div>

app/views/answers/_form.html.erb
<%= form_for [@question, @question.answers.new], remote: true do |f| %>
        
        <div class="form-group">
                <h5 class="mb-5">Si usted sabe o conoce de alguien que pueda ayudar con la respuesta, contribuya. Gracias!</h5>
            <%= f.text_area :content, class:"form-control", id: "content-answer", placeholder: "Escriba su posible respuesta", rows: 5 %>
        </div>
        <div class="actions">
            <%= f.submit 'Enviar', class: "btn btn-primary btn-sm" %>
        </div>
<% end %>

app/views/answers/create.js.erb
$('<%= escape_javascript(render(@answer))%>').appendTo('#answers-list');
$("#content-answer").val('');
$('#count-answers').html('<%= @question.answers.count() %>');

app/views/answers/destroy.js.erb
$('#answer-<%= @answer.id %>').remove();
$('#count-answers').html('<%= @question.answers.count() %>')
<!-- console.log('Estoy eliminando'); -->

app/views/comments/_comment.html.erb
<div class="col align-content-center">                            
    <label for=""><%= comment.content %></label> <br>
    <br>            
    <hr>
</div>

app/views/comments/_form.html.erb
<%= form_for [commentable, @question.comments.new], remote: true do |f| %>

    <div class="form-group">
        <%= f.text_area :content, class:"form-control", id: "content-comment", placeholder: "Escriba su comentario" %>
    </div>
    <div class="actions float-right">
        <%= f.submit 'Comentar', class: "btn btn-primary btn-sm" %>
    </div>

<% end %>

app/views/comments/create.js.erb
<% if @comment.commentable_type == "Answer"%>
    $("<%= escape_javascript(render(@comment)) %>").appendTo('#answer-<%= @comment.commentable_id %> #comments-answers-list');
    $('#answer-<%= @comment.commentable_id %> #content-comment').val('');
<% elsif @comment.commentable_type == "Question"%>
    $("<%= escape_javascript(render(@comment)) %>").appendTo('#question-comments-list');
    $('#content-comment').val('');
    <!-- $('span #count-comments-question').html('<%#= @question.comments.count() %>'); -->
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">
        <img src=" <%= image_path('jb-logo-4.png') %>" width="40" height="40" class="d-inline-block align-top" alt="">
        <span> Flow Overstack </span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
            <li><%= image_tag gravatar_url(current_user.email , 40), class: "rounded-circle" %></li>
            <li class="nav-item">
                <h6 class="nav-link">
                    <%= current_user.username %>
                </h6>
                <li class="mr-3">
                    <%= link_to "Salir", destroy_user_session_path, method: :delete, class: "nav-link" %>
                </li>            
          </li>
        <% else %>
            <li class="nav-item">
                <%= link_to "Ingresar", user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Registrarse", new_user_registration_path, class: "nav-link" %>
            </li>
        <% end %>        
    </ul>
    <%= form_tag questions_path, method: :get, class: "form-inline my-2 my-lg-0" do %>
        <%= text_field_tag :search, nil, class: "form-control mr-sm-2", placeholder: "Buscar" %>
        <%= submit_tag "Buscar", class: "btn btn-outline-success my-2 my-sm-0", type: "submit" %>
    <% end %>
    
     
    <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JBFlowoverstack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" type="text/css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="mb-5">
      <%= render 'layouts/navbar' %>
    </header>    
    
    <% flash.each do |key, msg|%>
      <div class='<%= flash_msg(key)%>' id='mensaje'>
        <p><%= msg %></p>
      </div>    
    <% end %>

      
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <h1>Preguntas</h1>
        </div>
        <div>
            <%= link_to  "Realizar Pregunta", new_question_path, class:"btn btn-primary btn-lg" %>
        </div>
    </div>
    <hr>
    <% @questions.each do |question|%>
        <div class="row question d-flex justify-content-end">   
            <div class="col-2 text center">
                <span>0</span>
                <span>Votos</span>
            </div>
            <div class="col-2 text center">
                <span><%= question.answers.count() %></span>
                <span>Respuestas</span>
            </div>
            <div class="col-8">
                <span><%= link_to  question.title, question %></span>
                
                <span>- Preguntó: <%= question.user.username %> hace <%= time_ago_in_words(question.created_at) %> </span>
            </div>
        </div>
        <hr>
    <% end %>
</div>

app/views/questions/new.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <h1><%= @question.new_record? ? "Publicar Pregunta" : "Editar Pregunta" %></h1>

            <% if @question.errors.any? %>
                    <ul>
                        <% @question.errors.full_messages.each do |message| %>
                            <li class="list-group-item list-group-item-danger"> <%= message %> </li>
                        <% end %>
                    </ul>
            <% end %>

            <%= form_for @question do |f| %>
                <div class="form-group">
                    <%= f.text_field :title, class: 'form-control form-control-lg', placeholder: "Titulo de la pregunta" %>
                </div>
                <div class="form-group">
                    <%= f.text_area :content, class: 'form-control form-control-lg', rows: 3, placeholder: "Escriba pregunta a realizar" %>
                </div>
                <div class="action">
                    <%= f.submit @question.new_record? ? "Crear Pregunta" : "Editar Pregunta", class: "btn btn-primary btn-lg" %>
                    <%= link_to  "Volver", root_path, class: "btn btn-link" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/questions/show.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <h1><%= @question.title %></h1>
        </div>
    </div>
    <div class="row mb-5">
        <div class="col-2 text-center" >
            <span class="fa fa-thumbs-o-up"></span>
            <br>
            <span>0</span>
            <br>
            <span class="fa fa-thumbs-o-down"></span>
        </div>
        <div class="col-10">           
            <div class="question">
                <span> <%= @question.content %></span>                
            </div>
            <hr>
            <%= link_to "Comentarios ", "#", class: 'show-comments', data: {'js-show-link' => true} %> <span id="count-comments-question">(<%= @question.comments.count()%>)</span>
            <div id="show-comments-question">
                <div class="mb-5" id="question-comments-list">
                        <%= render  @question.comments %>
                        <!-- muestra los comentarios de la pregunta -->
                </div>

                <div class="mb-5" id="question-comment-form">                    
                    <%= render "comments/form", commentable: @question %>
                    <!-- muestra el formulario para incluir un nuevo comentario a la pregunta -->
                </div>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col">
            <div class="mb-5">
                <h2>Respuestas (<span id="count-answers"><%= @question.answers.count()%></span>)</h2> 
                <hr>
            </div>            
        </div>
    </div>
    
    <div class="row" id="answers-list">
        <div class=" d-block">
            <%= render @question.answers.order(created_at: :ASC) %>            
        </div>
    </div>

    <div class="answer-form">
        <%= render 'answers/form'%>
        <!-- muestra el formulario de respuesta a esa pregunta -->
    </div>
</div>